### ISSUE TITLE
CredentialsError

### ISSUE THREAD

**Issue by malcolmcdixon** [alexa/skill-sample-nodejs-multi#4]
Hi,

Got a little further with this sample than the SmartHome Switch sample, at least the device was discovered but step 8 running the SQS message client fails:
Receive Error Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at Timeout.connectTimeout [as _onTimeout] (C:\Users\Malcolm\Nextcloud\Documents\Development\Alexa\skill-sample-nodejs-multi\client\node_modules\aws-sdk\lib\http\node.js:69:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'CredentialsError',
  time: 2021-03-09T15:43:09.624Z,
  retryable: true,
  originalError: {
    message: 'Could not load credentials from any providers',
    code: 'CredentialsError',
    time: 2021-03-09T15:43:09.624Z,
    retryable: true,
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      code: 'TimeoutError',
      time: 2021-03-09T15:43:09.624Z,
      retryable: true,
      originalError: [Object]
    }
  }
}

How to resolve this? Thanks.

**Comment by malcolmcdixon** [comment]
Always the way, post an issue then resolve it myself a little later!
I created a new IAM user that had full access to SQS permission.
Created a credentials.json file, see https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-json-file.html
Updated the code in client.js to include the following line before AWS.config.update({ region: region });
AWS.config.loadFromPath("./credentials.json");

Unsure why it didn't work for me without this though as I'm sure I followed the steps to the letter.
